update

diff --git a/jenkinsfolder/pipeline/agent/stage_conditions/Jenkinsfile b/jenkinsfolder/pipeline/agent/stage_conditions/Jenkinsfile
--- a/jenkinsfolder/pipeline/agent/stage_conditions/Jenkinsfile
+++ b/jenkinsfolder/pipeline/agent/stage_conditions/Jenkinsfile
@@ -1,1 +1,53 @@
+boolean testPassed = true
+pipeline {
+    agent any
+    stages {
+        stage('Build'){
+            steps{
+                echo "Build stage........."
+                sh 'sleep 5'
+            }
+        }
+    stage('Test'){
+        steps {
+            script {
+                try{
+                    echo "Running test cases....."
+                    sh 'sleep 5
+                    s 'exit 1'
+            
+                }catch (Eception e){
+                    echo "Test case failed......."
+                    testPassed = false
+                }
+            }
+        }
+    }
+    stage('Deploy'){
+        steps {
+            script {
+                if(testPassed){
+                    echo "Deploying to test environment..."
+                    sh 'sleep 5'
+                    sh 'exit 1'
+                } else {
+                    echo "skipping deployment ......"
+                }
+            }
+        }
+    }
+    stage('Mail'){
+        steps{
+            script {
+                if(!testPassed){
+                    echo "Sending mail on test fail"
 
+                } else {
+                    echo "sending mail on deployment success"
+                }
+            }
+        }
+    }
+    }
+
+}
